number = 4
slug = "ocaml-smoke-test"
status = "completed"
description = """
# Step: ocaml-smoke-test

Prove that the `sw-cor24-ocaml` toolchain at
`~/git..."""
role = "production"
context_files = []
created_at = "2026-04-24T18:45:32"
completed_at = "2026-04-24T19:24:01"
commits = ["6de1bb1e06a0b12856e41ea7afd4cdd41020770a"]
