type token = TIdent of string | TInt of int | TPct of int | TMinus | TLArrow | TRArrow | TLParen | TRParen | TLBrace | TRBrace | TComma | TUnderscore | THash of string | TLiteral of string | TUnknown of int | TEOF | TMint
let token_name t = match t with TIdent s -> "ident:" ^ s | TInt n -> "int:" ^ string_of_int n | TPct n -> "pct:" ^ string_of_int n | TMinus -> "minus" | TLArrow -> "larrow" | TRArrow -> "rarrow" | TLParen -> "lparen" | TRParen -> "rparen" | TLBrace -> "lbrace" | TRBrace -> "rbrace" | TComma -> "comma" | TUnderscore -> "slot" | THash s -> "comment:" ^ s | TLiteral s -> "lit:" ^ s | TUnknown n -> "unknown:" ^ string_of_int n | TEOF -> "eof" | TMint -> "mint"
let is_error_node n = match n with AError s -> true | _ -> false
let rec skip_trivia toks = match toks with [] -> [] | h :: t -> (match h with THash _ -> skip_trivia t | _ -> toks)
let is_expand_token t = match t with TIdent s -> s = "expand" | TLiteral s -> s = "expand" | _ -> false
let is_syntax_head toks = match toks with TMint :: TIdent s :: t -> s = "syntax" | TMint :: TLiteral s :: t -> s = "syntax" | _ -> false
let rec has_assign toks = match toks with [] -> false | h :: t -> (match h with TLArrow -> true | TEOF -> false | _ -> has_assign t)
let rec parse_group_items kind close_tok toks acc = match toks with [] -> (AError ("unterminated-" ^ kind), []) | h :: t -> if h = close_tok then (AGroup (kind, List.rev acc), t) else (match h with TEOF -> (AError ("unterminated-" ^ kind), toks) | TUnknown n -> (AError ("unknown-token:" ^ string_of_int n), t) | THash _ -> parse_group_items kind close_tok t acc | _ -> parse_group_items kind close_tok t ((token_name h) :: acc))
let rec parse_kernel_items toks acc = match toks with [] -> (AStmt ("kernel", List.rev acc), []) | h :: t -> (match h with TEOF -> (AStmt ("kernel", List.rev acc), toks) | THash _ -> parse_kernel_items t acc | TUnknown n -> (AError ("unknown-token:" ^ string_of_int n), t) | TLParen -> let pair = parse_group_items "paren" TRParen t [] in let node = fst pair in let rest = snd pair in if is_error_node node then (node, rest) else parse_kernel_items rest (node :: acc) | TLBrace -> let pair = parse_group_items "brace" TRBrace t [] in let node = fst pair in let rest = snd pair in if is_error_node node then (node, rest) else parse_kernel_items rest (node :: acc) | _ -> parse_kernel_items t ((AAtom (token_name h)) :: acc))
let rec parse_expansion toks acc = match toks with [] -> (AGroup ("expansion", List.rev acc), []) | h :: t -> (match h with TEOF -> (AGroup ("expansion", List.rev acc), toks) | THash _ -> parse_expansion t acc | TUnknown n -> (AError ("unknown-token:" ^ string_of_int n), t) | _ -> parse_expansion t ((token_name h) :: acc))
let rec parse_template toks acc = match toks with [] -> (AError "syntax-missing-expansion", []) | h :: t -> if is_expand_token h then let pair = parse_expansion t [] in let exp = fst pair in let rest = snd pair in if is_error_node exp then (exp, rest) else (AStmt ("syntax-expand", [AGroup ("template", List.rev acc); exp]), rest) else (match h with TRArrow -> let pair = parse_expansion t [] in let exp = fst pair in let rest = snd pair in if is_error_node exp then (exp, rest) else (AStmt ("syntax-verb", [AGroup ("template", List.rev acc); exp]), rest) | TEOF -> (AError "syntax-missing-expansion", toks) | THash _ -> parse_template t acc | TUnknown n -> (AError ("unknown-token:" ^ string_of_int n), t) | _ -> parse_template t ((token_name h) :: acc))
let parse_syntax toks = match toks with TMint :: TIdent s :: t -> parse_template t [] | TMint :: TLiteral s :: t -> parse_template t [] | _ -> (AError "expected-syntax-head", toks)
let parse_statement toks = match toks with [] -> (AError "expected-token", []) | h :: t -> (match h with TEOF -> (AError "expected-token", toks) | THash _ -> (AError "expected-token", t) | TUnknown n -> (AError ("unknown-token:" ^ string_of_int n), t) | _ -> if is_syntax_head toks then parse_syntax toks else let pair = parse_kernel_items toks [] in let node = fst pair in let rest = snd pair in if is_error_node node then (node, rest) else if has_assign toks then (match node with AStmt (kind, xs) -> (AStmt ("assign", xs), rest) | _ -> (node, rest)) else (match node with AStmt (kind, xs) -> if h = TMint then (AStmt ("mint", xs), rest) else (node, rest) | _ -> (node, rest)))
let rec parse_program toks acc = let rest = skip_trivia toks in match rest with [] -> AProgram (List.rev acc) | h :: t -> (match h with TEOF -> AProgram (List.rev acc) | _ -> let pair = parse_statement rest in let node = fst pair in let after = snd pair in if is_error_node node then node else parse_program after (node :: acc))
let parse toks = parse_program toks []
